/*------------------------------------------------------------------------
    File        : ITaskProcessor
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : chthomso@progress.com
    Created     :
    Notes       : 
  ----------------------------------------------------------------------*/

interface psc.tasks.ITaskProcessor:  
    method public integer runAllScheduledTasks().  
end interface.